### ISSUE TITLE
Diagram Editor: Support bidirectional edges

### ISSUE THREAD

**Issue by till-f** [JetBrains/MPS-extensions#110]
provide API / extend diagram language so that application developer can set the “direction” information
provide API / extend diagram language so that application developer can configure edge endpoint shapes accordingly (e.g. arrow, dot, diamond, ...)

**Comment by alexanderpann** [comment]
I don't understand the first part of the request. For edges, you can set information for the _from_ and _to_ endpoints. Setting the shapes is possible as well.

**Comment by alexanderpann** [comment]
I close it because it seems already implemented.
