### ISSUE TITLE
Diagram: Missing diagram representation for children

### ISSUE THREAD

**Issue by arimer** [JetBrains/MPS-extensions#139]
When switching from the default represenation to the diagram representation some children are not rendered at all. In fact, the children are not part of the diagram editor and therefor no error markes (from TS/Non-TS rules) are shown when diagram view is activated.

The screenshot shows a component in default and diagram representation

**Default view:** Showing instances with parameters and error marker

![grafik](https://user-images.githubusercontent.com/16648247/48773185-f1404180-ecc6-11e8-9ade-9a89e8c297ee.png)

**Diagram view:** Parameters diagram editor is missing, error markers not at the node containing the error

![grafik](https://user-images.githubusercontent.com/16648247/48773250-1cc32c00-ecc7-11e8-9f25-2e16a0aad491.png)

Example was created with MPS 2018.2.3 and following versions:

mbeddrPlatformArtifacts: 
```
org.iets3.analysis:z3: 0.1.3744.b749267 
org.iets3:core: 0.1.3744.b749267
```

**Comment by coolya** [comment]
From what I understand from description is that the diagram editor does not show errors for children correctly? 

The error marker is attached to the wrong place (only on the root node) and not on the last ancestor that is shown in the editor. Right?

**Comment by arimer** [comment]
This is one problem, yes. 

The other problem is, that the diagram editor for the children of the rendered node (in our case the `ParameterValue` of a `ComponentInstance`) is not applied. 

Priviously the `ParameterValue` was visibile in the diagram editor, but now it is not.

**Comment by coolya** [comment]
As far as I can see this isn't really related to the diagram framework. Looking at the editor definitions in IETS3. The editor component `ComponentInstanceBase_Diagram_Footer` is simply no longer part of the editor definition of the `AbstractComponentInstanceBase` editor and therefore no parameter values are shown.
