### ISSUE TITLE
Documentation issues (Readme, Contributing)

### ISSUE THREAD

**Issue by digital-ember** [JetBrains/MPS-extensions#154]
* It would be nice if the README or the linked "Contributing" page would explain what one needs in order to contribute (IntelliJ IDEA, for example, doesn't seem to be mentioned anywhere. At least I think it is required...)
* the linked "Contributing" page has 
  * a dead link (to https://jetbrains.github.io/Migration)
  * a link to no issues (good first issues there are non at the moment, which I guess is a valid state, but maybe a bit disappointing if people want to get started)

**Comment by fvollmer** [comment]
I think it would be super useful to have at least *one sentence of documentation* for every extension. At the current state it isn't obvious what the use cases of all the different extensions are. By just looking at the code folder you can see:

- **blutil** ❔
- **celllayout** ❔
- **conditional-editor** ❔
- **diagram** ✔ (https://jetbrains.github.io/MPS-extensions/extensions/diagrams/)
- **grammarcells** see https://dl.acm.org/citation.cfm?doid=2997364.2997365
- **hacks** ❔
- **languages** ❔ appears to be connected to the model merger?
- **math** ❔ provides some math like looking editors for symbols, sums etc.
- **mouseselection** ❔
- **multiline** ❔
- **nodeversioning** ✔ (https://jetbrains.github.io/MPS-extensions/extensions/node-versioning/)
- **plaintextgen** ✔ (https://github.com/JetBrains/MPS-extensions/tree/master/code/plaintextgen)
- **richtext** ❔ Provides some text based editor features.
- **shadowmodels** ✔ https://github.com/JetBrains/MPS-extensions/blob/master/code/shadowmodels/README.md
- **solutions** ❔ appears to be connected to the model merger?
- **structurecheck** ❔
- **tables** ❔ A implementation of tables for the mps editor with more advanced features than the original one from jetbrains.
- **tooltips** ❔ I guess the name says it
- **utils/solutions** ❔
- **widgets**  ❔

For the most of the extensions there is close to zero information and in my opinion a short description of the extension would already be useful!
