### ISSUE TITLE
Add @eugenschindler as a contributor

### ISSUE THREAD

**Issue by coolya** [JetBrains/MPS-extensions#159]
@eugenschindler is going to maintain the plaintext gen part of the MPS extensions in the future hence he should have maintainer access to this repository so that he can review pull requests and merge changes.

**Comment by eugenschindler** [comment]
Any idea on the ETA of doing this? I'd like to assign a label to an issue for plaintextgen and migrate the other issues from the original plaintextgen repository to here.

**Comment by JoostvanPinxten** [comment]
Looks like this issue can be closed?
