### ISSUE TITLE
Extensions button of the navigation bar at the website is broken

### ISSUE THREAD

**Issue by fvollmer** [JetBrains/MPS-extensions#163]
The mps-extensions website (https://jetbrains.github.io/MPS-extensions/) is broken for me. I can't use the Extensions button of the navigation bar (I tried multiple web browsers).

![grafik](https://user-images.githubusercontent.com/16699443/51034834-4d796080-15a8-11e9-8ce0-18b947fe55ce.png)

**Comment by coolya** [comment]
Seems like it's related to an issue with the mkdocs theme that we are using chrissimpkins/cinder#59

I'm going to update the theme on the build server and then regenerate the documenation.

**Comment by coolya** [comment]
Build server was updated and documentation was redeployed. The issues seems fixed now.

I also opened #164 to make updating mkdocs and its dependencies easier.
