### ISSUE TITLE
ShapeDefinition drawShadow defaults to a gray drop shadow, when "no drawShadow" is defined

### ISSUE THREAD

**Issue by JoostvanPinxten** [JetBrains/MPS-extensions#168]
When a `de.itemis.mps.editor.diagram.ShapeDefinition` has no `drawShadow` defined, it shows by default a dropShadow:

![dropShadow](https://user-images.githubusercontent.com/3332970/51970783-0a5c3000-2478-11e9-9e70-fc4ba00ecaa1.png)

![editor](https://user-images.githubusercontent.com/3332970/51970630-b2bdc480-2477-11e9-96fa-368fc8a0e01d.png)

Only when this is overridden with an empty `Function_DrawShadow` the drop shadow disappears.

Suggestion: either define the text for an empty `Function_DrawShadow` to say 'default drop shadow` or add options to draw 'none', 'default', or 'custom' shadows.

**Comment by alexanderpann** [comment]
Fixed in https://github.com/JetBrains/MPS-extensions/commit/4cb8baf190d5f0bf31d0ed6b42dad4dfac0fddf4.
