### ISSUE TITLE
MapReduce in language com.mbeddr.mpsutil.blutil is broken 

### ISSUE THREAD

**Issue by fisakov** [JetBrains/MPS-extensions#175]
MapReduce uses an instance of UnWrite, which no longer generates working code. 

The test case test_mapReduce does not pass.

**Comment by arimer** [comment]
An instance of the *deprecated* `UnWrite` concept is used in this [reduction rule](http://127.0.0.1:63320/node?ref=3a6b9f2f-4402-4ed6-a7cd-12b272b244d5%2Fr%3A0d8c18c2-3a01-472e-96fe-573575c47352%28com.mbeddr.mpsutil.blutil%23374287044672169667%2Fcom.mbeddr.mpsutil.blutil.generator.template.main%40generator%29%2F6534474553327082080&project=mps-extensions) and produces invalid code.
