### ISSUE TITLE
Remove stale branch plaintext-gen

### ISSUE THREAD

**Issue by eugenschindler** [JetBrains/MPS-extensions#198]
I would like to remove https://github.com/JetBrains/MPS-extensions/tree/plaintext-gen. 
I think this branch was meant to help me integrate https://github.com/DSLFoundry/mps-plaintextgen repository to MPS-extensions, which has now been accomplished.
Is my assumption correct, and is it OK with you to remove the branch, @coolya?

**Comment by alexanderpann** [comment]
The branch was removed.
