### ISSUE TITLE
NodeToSNodeAdapter produces nodes with not comparable references

### ISSUE THREAD

**Issue by arimer** [JetBrains/MPS-extensions#205]
When comparing an "original" `SNode` with an `NodeToSNodeAdapter.wrap(INode)` using the 
**AssertNodeEquals** asserts from the `com.mbeddr.mpsutil.compare` language, the result is true, regardless the reference targets of the actual node.

Although the returned shadow model contains references (with same link) pointing the different target nodes, the **AssertNodeEquals** compare does not complain. 

Looks like the `NodeToSNodeAdapter` implements the "reference" methods differently.

**Comment by slisson** [comment]
Fixed in c787286ee2cf7c81ad2805c71b105e7923be8f48
