### ISSUE TITLE
Migrate com.mbeddr.mpsutil.varscope

### ISSUE THREAD

**Issue by coolya** [JetBrains/MPS-extensions#21]
Migrate com.mbeddr.mpsutil.varscope

Url: http://127.0.0.1:63320/node?ref=r%3A742f344d-4dc4-4862-992c-4bc94b094870%28com.mbeddr.mpsutil.dev.build%29%2F7414963977311190157&project=com.mbeddr.build

see migration guide at: https://jetbrains.github.io/MPS-extensions/Migrating/

**Comment by alexanderpann** [comment]
I am closing because the language is deprecated and doesn't need to be migrated to this repository.
