### ISSUE TITLE
Migrate com.mbeddr.mpsutil.editor.querylist

### ISSUE THREAD

**Issue by coolya** [JetBrains/MPS-extensions#23]
Migrate com.mbeddr.mpsutil.editor.querylist

Url: http://127.0.0.1:63320/node?ref=r%3A742f344d-4dc4-4862-992c-4bc94b094870%28com.mbeddr.mpsutil.dev.build%29%2F7231064182705610173&project=com.mbeddr.build

see migration guide at: https://jetbrains.github.io/MPS-extensions/Migrating/

**Comment by alexanderpann** [comment]
Closing because the language was already migrated.
