### ISSUE TITLE
Migrate com.mbeddr.mpsutil.processwizard

### ISSUE THREAD

**Issue by coolya** [JetBrains/MPS-extensions#24]
Migrate com.mbeddr.mpsutil.processwizard

Url: http://127.0.0.1:63320/node?ref=r%3A742f344d-4dc4-4862-992c-4bc94b094870%28com.mbeddr.mpsutil.dev.build%29%2F6047264936605751488&project=com.mbeddr.build

see migration guide at: https://jetbrains.github.io/MPS-extensions/Migrating/

**Comment by alexanderpann** [comment]
I guess `com.mbeddr.mpsutil.processwizard` was renamed to `com.mbeddr.mpsutil.process`. Based on the current categorisation of languages, we can keep it in mbeddr.
