### ISSUE TITLE
The file encoding in the TextgenText_TextGen is hard wired to UTF-8

### ISSUE THREAD

**Issue by KemalSoysal** [JetBrains/MPS-extensions#241]
When using the TextgenText for file output the file encoding is always UTF-8.
This should be configurable

**Comment by KemalSoysal** [comment]
The version I needed the fix for is MPS 2018.2.6
Since there is no maintenance branch for the 2018.2.6, I forked the maintenance/20182 branch from the original DSLFoundry/mps-plaintextgen. You can find the proposed chang in the fork here: https://github.com/ls-it-solutions/mps-plaintextgen/commits/maintenance/mps20182
in the commits 23b04a019d5b48a363367940911dd8a1a537c00b and eac1d74c3c079b78e50ffa946ebbbf5a489ef239

**Comment by JoostvanPinxten** [comment]
This sounds like a welcome addition. Can you please implement this for the master branch as well? This way this nice feature has much higher chance to be integrated in new releases of MPS Extensions.

**Comment by KemalSoysal** [comment]
done with pull request #243

**Comment by JoostvanPinxten** [comment]
I just noticed that this change was added to our local installation :-) I hadn't noticed that the pull request had already been completed, and we completely forgot to thank you for your contribution! 

So here goes: thanks for your contribution @KemalSoysal!
