### ISSUE TITLE
Link to more advanced tutorial for diagram editor

### ISSUE THREAD

**Issue by eugenschindler** [JetBrains/MPS-extensions#246]
It may also be good to add a link to http://dslfoundry.com/using-the-diagram-editor-and-querylist-lets-build-a-graphical-structure-editor-for-mps/ for a bit more of an advanced tutorial on the subject. Maybe in time such a tutorial can also be properly transferred to the docs here.

**Comment by alexanderpann** [comment]
I am closing because the [tables documentation page](https://jetbrains.github.io/MPS-extensions/extensions/editor/tables/#blog-posts) now has 2 links to external blog posts and can be further extended if needed.
