### ISSUE TITLE
Shadow Models: Support writing transformation output to the input repository

### ISSUE THREAD

**Issue by slisson** [JetBrains/MPS-extensions#251]
Currently, the input models and output models are strictly separated to avoid dependency cycles. There are use cases were it is useful to also update the input model (see https://github.com/ModelingValueGroup/DclareForMPS).

An attempt was made to run an MPS generator on a (transient) shadow model, but since it doesn't exist in the file system, the integration causes too many problems without easy workarounds. One solution is to synchronize the output to a normal MPS Solution instead of the special transient SModule/SModel.

**Comment by eugenschindler** [comment]
Is it resolved or just removed because it is too old?

**Comment by slisson** [comment]
There is limited support for it (only what our use case requires). You can specify the module id of an existing solution and then the output is written to that module instead of a transient module.
