### ISSUE TITLE
Migrate com.mbeddr.codereview

### ISSUE THREAD

**Issue by coolya** [JetBrains/MPS-extensions#27]
Migrate com.mbeddr.codereview

Url: http://127.0.0.1:63320/node?ref=r%3A742f344d-4dc4-4862-992c-4bc94b094870%28com.mbeddr.mpsutil.dev.build%29%2F7005560613509858789&project=com.mbeddr.build

see migration guide at: https://jetbrains.github.io/MPS-extensions/Migrating/

**Comment by alexanderpann** [comment]
I am closing because this language was not used for many years and there is no reason to migrate it anymore.
