### ISSUE TITLE
Export of Diagrams from Build

### ISSUE THREAD

**Issue by bkolb** [JetBrains/MPS-extensions#293]
I am using the HeadlessEditorComponent to export images in the build.
For Diagrams this does not work
![ADF](https://user-images.githubusercontent.com/355333/78891435-d7dc9880-7a67-11ea-99e2-1094a3d446b5.png)

I have this code:
```
cell = new HeadlessEditorComponent(outsideComp, node.model/.getRepository()).getRootCell()
CellEditorScreenshooter.writeImage(cell, filename)
```

**Comment by slisson** [comment]
You need to call .setSize and .relayout on the EditorComponent to properly render cells containing swing components.

Why do you create your own HeadlessEditorComponent? You can just use com.mbeddr.core.base.pluginSolution.plugin.CellEditorScreenshooter.takeScreenshot.

**Comment by bkolb** [comment]
Ok! thx! Will use that.
