### ISSUE TITLE
Word behavior for getText / setText does not escape/unescape the strings

### ISSUE THREAD

**Issue by danielratiu** [JetBrains/MPS-extensions#311]
The methods getText / setText of the Word-behavior, use MultilineUtil - escapeText / unescapeText methods. These methods have empty implementations (screenshot below).

![image](https://user-images.githubusercontent.com/1437141/89134076-54691a80-d522-11ea-80e6-059675f64c67.png)

**Comment by coolya** [comment]
I don't understand this issue, the comments in the method stat that escaping is obsolete so these methods only exist to make the code compile. I think they should be marked as deprecated.

**Comment by eugenschindler** [comment]
@danielratiu would it be an acceptable solution to mark these methods as deprecated, as proposed by @coolya?

**Comment by alexanderpann** [comment]
I have deprecated the methods in 1595ede.
