### ISSUE TITLE
`named.conf` for ISC Bind9

### ISSUE THREAD

**Issue by egberts** [JetBrains/MPS-extensions#329]
Bind9 is a robust industry-standard DNS nameserver.

Bind9 configuration file for `named` daemon has over 200 nodes in its parser tree.

Be nice if we could get the same thing from Jet Brian editor session to provide MPS on `named.conf` file for Bind9.

**Comment by slisson** [comment]
Did you accidentally created this issue in the wrong repository?

**Comment by egberts** [comment]
Ouch.  My apology...

Was only responding to https://jetbrains.github.io/MPS-extensions/contributing/
