### ISSUE TITLE
Deploy de.60.mps.libs to Marketplace

### ISSUE THREAD

**Issue by tillschallau** [JetBrains/MPS-extensions#336]
Installing the "de.itemis.mps.editor.diagram" plugin through the MPS Marketplace is failing, as the "de.q60.mps.libs" dependency is not automatically resolved. 

To resolve this, I had to build MPS-Extension and manually copy the plugin.

Possibly referencing issue #292 

Current MPS Version: 2020.2

**Comment by wsafonov** [comment]
I guess, `de.q60.mps.libs` ist not the only plugin from the dependencies that is missing on the Marketplace. The selection there is rather random. @slisson do you know who is maintaining the list of plugins that should be published to the Marketplace?

@tillschallau as an alternative to JetBrains Marketplace, if you want to use multiple languages from MPS-extensions, you'd probably better download the complete languages library package for MPS-extension from here: https://projects.itemis.de/nexus/content/repositories/mbeddr/de/itemis/mps/extensions/

**Comment by nolisj** [comment]
I'm also having the same problem for MPS 2020.3.

[Screenshot: Missing de.q60.mps.lib](https://imgur.com/lCnrUlh)

**Comment by eugenschindler** [comment]
@wsafonov I'll give you an answer via email, since not everything around the marketplace action has been completed yet.
@nolisj no, shadowmodels is not paid. As @wsafonov has said, you can get the full set of plugins either by building it yourself using gradlew or just pluck it off the Itemis Nexus (https://projects.itemis.de/nexus/content/repositories/mbeddr/de/itemis/mps/extensions/).

**Comment by eugenschindler** [comment]
@mvlassiev could this be a dependency problem? Maybe you can have a brief look why this dependency for the diagram editor is not deployed? Thanks a lot in advance!

**Comment by alexanderpann** [comment]
I am closing this issue because it is outdated.  All plugins are now published to the marketplace (including `de.q60.mps.collections.libs`). They are only available up to MPS 2021.2.6 though, but this is a completely unrelated topic.
