### ISSUE TITLE
Migrate com.mbeddr.mpsutil.json

### ISSUE THREAD

**Issue by coolya** [JetBrains/MPS-extensions#34]
Migrate com.mbeddr.mpsutil.json

Url: http://127.0.0.1:63320/node?ref=r%3A742f344d-4dc4-4862-992c-4bc94b094870%28com.mbeddr.mpsutil.dev.build%29%2F933071688407982433&project=com.mbeddr.build

see migration guide at: https://jetbrains.github.io/MPS-extensions/Migrating/

**Comment by sheldonrobinson** [comment]
[0001-Issue-Migrate-commbeddrmpsutiljson-34.patch.txt](https://github.com/JetBrains/MPS-extensions/files/3358145/0001-Issue-Migrate-commbeddrmpsutiljson-34.patch.txt)

**Comment by alexanderpann** [comment]
Let's close all those ancient `migrate` tickets. I'd rather extract those languages into separate projects to keep this platform slim. We must also evaluate all languages if they are polished enough to migrate anyway.
