### ISSUE TITLE
Broken layout in tables during editing

### ISSUE THREAD

**Issue by alex-y-wd** [JetBrains/MPS-extensions#341]
The issue was supposedly introduced in 9fd9f172f8e2a3c4ab6d6c3aaa90977ce3b2c0d1.
Editing a text value in the following table
<img src="https://user-images.githubusercontent.com/71335047/105050246-dff14c00-5a6d-11eb-84c5-ab7577bbe2a9.png" width="400">
leads to:
<img src="https://user-images.githubusercontent.com/71335047/105050184-cf40d600-5a6d-11eb-8f04-731facbeba68.png" width="400">

A test project to reproduce (you need to specify a location of mbeddr.platform in `Project Libraries`):
[test-project.zip](https://github.com/JetBrains/MPS-extensions/files/5841535/test-project.zip)

The MPS version is 2020.2.3.

**Comment by coolya** [comment]
I this on master with MPS 2002.3 or an older version MPS?

**Comment by alex-y-wd** [comment]
@coolya I updated the description.

**Comment by szabta89** [comment]
@coolya We saw this on the 2020.2 branch. The issue comes and goes. Once this was fixed, then @slisson fixed it, but the above mentioned commit broke the fix.

**Comment by coolya** [comment]
I wanted to make sure it's not a regression as part of the 2020.3 migration. thx for adding the info.

**Comment by szabta89** [comment]
@slisson In https://github.com/JetBrains/MPS-extensions/pull/352 you wrote that that PR maybe fixes this problem, too. It does not. CC @alex-y-wd

**Comment by alex-y-wd** [comment]
Thanks for the fix, tested it successfully.
