### ISSUE TITLE
Durchblick/plaintextgen

### ISSUE THREAD

**Issue by eugenschindler** [JetBrains/MPS-extensions#350]
If/when the Durchblick extension (which helps to visualize generator templates in a more "Xtexty" way) goes into MPS Extensions, it may be good to see how it interacts with plaintextgen and maybe test some important use cases with it.

**Comment by coolya** [comment]
There are no plans to move the  Durchblick plugin into MPS extensions.

**Comment by eugenschindler** [comment]
Is there anything concrete known about the Durchblick plugin? Usage, usefulness, maybe plans? I reallly wonder if it helps people or if it would help people more if we would make it more accessible?

**Comment by coolya** [comment]
It's used by some people, I don't have concrete numbers because there are no stats that would allows me collect these. If it helps people, I don't know, at least the users I talked to think it's useful. I also don't know how could be "more accessible" you can install it with a single click from the marketplace.

**Comment by eugenschindler** [comment]
Thanks for your explanation. Well, I don't have all the solutions, but I know that, in addition to being asked by people to add some of the DSLFoundry extensions to the MPS-Extensions community repo and the obvious help in terms of maintenance effort and uniform build infrastructure that connects well to the Itemis/JetBrains way-of-working for non-core (or not yet core) MPS extensions, I have another driver to add things like plaintextgen to MPS extensions: the availability becomes easier to people in a bigger company (like the company where I work) with corporate firewalls that prevent direct access to the JetBrains marketplace and a more strict version-management of plugins if such plugins are made available as part of the normal infrastructure that we have to import anyway (like mbeddr and MPS-Extensions). This may not be the best way of making things more accessible to such corporate kinds of users, but it helps in a way.
Just another tangential question (which I hope is not too off-topic): is there anywhere a list of the benefits for having plugins in the MPS-Extensions repository (benefits for the people developing extensions that they choose to host at MPS-extensions, but also benefits for end-users)? I can imagine some reasons (in part what I was writing up here), but it may be good to make them explicit.

**Comment by coolya** [comment]
Such a list does not exist, for the individual developer there aren't any real benefits I would say. MPS-extensions was formed primarily to decouple the none C specific parts, known as the mbeddr platform, from mbeddr branding but also infrastructure wise. The main purpose of MPS extension is to create a well maintained repository of useful extensions to MPS for language engineers. 
Adding more and more, sometime barely maintained, components to the this repository largely defeats the goal of having a well maintained and actively developed set of extensions. With our experience in the mbeddr platform it does not help to have large quantity of extensions but aim for quality. This is one of the reasons why the mbeddr platform was not transferred in bulk but step by step to ensure everything that is transferred is in good shape. With the current size of maintenance team, 2 people part time, there is little room for expansion. 
That extensions in this repository gain visibility is merely a secondary goal, for instance MPS extension developers do not have access to the mechanics in place to publish the plugins to the marketplace etc. Moving code into MPS extension to circumvent corporate open source policies is something I think we can't aim for, we can not fix a broken process inside a company by just moving more stuff here. 
I know it looks tempting to just move everything that is somehow related to MPS here but please keep in mind people build custom RCPs based on MPS and MPS extensions where bloat is a real concern. It's not that easy to balance all these concerns especially with limited amount of people actively contributing to MPS extensions. 
The current "team" involved in MPS extensions consists of two people that spend marginal time on it when required, e.g. for releases or urgent bugfixes and then there is you and Joost. Other than that there are no substantial contributions happening. The efforts in moving things from MPS extensions into MPS have been stopped to my knowledge. The only thing was moved was back in 2019 the tooltips.

**Comment by eugenschindler** [comment]
Thank a lot for all the explanations.
