### ISSUE TITLE
mps-tables don't accept a style for an entire row.

### ISSUE THREAD

**Issue by silviacroce** [JetBrains/MPS-extensions#36]
When trying to set a style to a horizontal r<> node it causes a compilation error.

The code I used is:

```
<no base style> {                                                                                                 
  apply-if : SampleStyle condition: (editorContext, node)->boolean { 
         true; 
 }
}         
```                                                                                                        

The compilation error is:

`com/SampleConcept_EditorBuilder_a.java : Syntax error on token ",", Expression expected after this token`

The generated code is:

`new SampleStyleClass(getEditorContext(), getNode()).apply(style, );`

**Comment by slisson** [comment]
https://github.com/mbeddr/mbeddr.core/issues/1913
