### ISSUE TITLE
Border styles break layout for function parameters

### ISSUE THREAD

**Issue by alex-y-wd** [JetBrains/MPS-extensions#391]
Editing the number in the method body below leads to the following broken layout.
Before:
![image](https://user-images.githubusercontent.com/71335047/116887805-01480380-ac2b-11eb-9ba2-79c13531ef83.png)
After:
![image](https://user-images.githubusercontent.com/71335047/116887820-06a54e00-ac2b-11eb-82f8-efb459f1fede.png)

I've seen this particularly with `_border-top-size and` and `_border-top-color` (defined on the `TestFragment_Editor` in the attached sample).

[test-project.zip](https://github.com/JetBrains/MPS-extensions/files/6415458/test-project.zip)

**Comment by alex-y-wd** [comment]
Hey @slisson 
is there any update on this?

**Comment by slisson** [comment]
No

**Comment by alexanderpann** [comment]
Not reproducible anymore. We fixed a few related issues that looked exactly like this.
