### ISSUE TITLE
Change Grammar Cells Editor Layout to Indent Layout

### ISSUE THREAD

**Issue by Kiibou-chan** [JetBrains/MPS-extensions#415]
Currently many (if not all, I did not check) grammar cell concepts use the horizontal layout in their editor. It would be useful if those could be changed to indent layout. With indent layout the component in the editor cell (in an optional for example) stays completely on the same level as the component that uses the editor cell, currently that does not happen.

Changing this gives more flixibility in general as it is up to the user of the grammar cell what layout they want.

Examples:
This uses indent layout:
![image](https://user-images.githubusercontent.com/20756868/123068351-1adb1f80-d412-11eb-8d3a-ee9aea37c7d8.png)

Used in another component with indent layout it can look like this (return is a separate component):
![image](https://user-images.githubusercontent.com/20756868/123068417-2a5a6880-d412-11eb-8d62-07e009dd9ee3.png)

Here I use an optional grammar cell for the "= ..." part. Because of the horizontal layout in the grammar cell it does not indent nicely:
![image](https://user-images.githubusercontent.com/20756868/123068602-5249cc00-d412-11eb-901a-5524f3c17361.png)

**Comment by slisson** [comment]
I assume your editor definition looks similar to this: 
<img width="273" alt="Screenshot 2021-06-23 at 11 11 56" src="https://user-images.githubusercontent.com/1543361/123070236-dfd9eb80-d413-11eb-8dd2-ef2e34f5f977.png">

You should be able to just change the "cell layout" of the collection cell to "indent".

**Comment by Kiibou-chan** [comment]
That actually did it, thanks a lot.
