### ISSUE TITLE
Empty About section for this repository

### ISSUE THREAD

**Issue by eugenschindler** [JetBrains/MPS-extensions#416]
The about section of this repository is empty. I think it would be good to add something from the README or another concise explanation about this repository in the About section of this repository.

**Comment by eugenschindler** [comment]
@coolya is it possible that you copy the first 1-2 sentences in the description or give me permisson to do so?

**Comment by coolya** [comment]
@eugenschindler I don't have permissions to this in this repo either.

**Comment by eugenschindler** [comment]
Thanks for the info. Maybe @mvlassiev can help here?

**Comment by slisson** [comment]
@ashatalin is the owner of this repository. He can change it.

**Comment by ashatalin** [comment]
@eugenschindler I copied first sentence from the README to the about section. The second sentence looks too long for this text. ;-)
