### ISSUE TITLE
.gitignore may not be up-to-date

### ISSUE THREAD

**Issue by eugenschindler** [JetBrains/MPS-extensions#418]
Since MPS 2021.1, I get the following after a build in clean git working copy:
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	scripts/.mps-caches/

nothing added to commit but untracked files present (use "git add" to track)

This would suggest that we may want to update the .gitignore with an entry like:
`.mps-caches`

@dbinkele would you agree with this or am I overlooking something suggesting this?

**Comment by dbinkele** [comment]
@eugenschindler What project are you talking about mbeddr? iets3.os? iets3.core? Currently only mbeddr is migrated to 2021.1 ......

**Comment by eugenschindler** [comment]
@dbinkele The project is just MPS Extensions itself. That's why I posted the issue on the MPS Extensions repository.

**Comment by dbinkele** [comment]
@eugenschindler I checked out MPS-extensions and did a clean built, too. Then I simply opened it with a MPS2021.1, but did not have the above issue. Even after a project rebuilt in the IDE. Did you do something spefific?

**Comment by eugenschindler** [comment]
@dbinkele I did an MPS-extensions build (gradlew) on a fully cleanly checked out MPS-extensions repo in Windows and in Linux (unfortunately I don't have Mac for testing) and both of them show me this scripts/.mps-caches as new unknown files in git. I have done nothing special, just ran a gradlew.
Could it be that you (or maybe some internal setup guideline or process in your project(s)) changed something in your global (or local) git settings to ignore this scripts/.mps-caches? I know that git nowadays also allows for storing local ignores that are not checked in by putting them in .git/info/exclude.
