### ISSUE TITLE
Selection in diagrams is NOT reflected in the Documentation view

### ISSUE THREAD

**Issue by ratiud** [JetBrains/MPS-extensions#428]
I have a language (components) which has documentation aspect. Documentations can be attached to components.

This language has two notations: a textual and a graphical (diagrammatic) one.
In textual notation, when I click on a component reference, the documentation window is updated as expected.
In diagrammatic view, when I click on the Box corresponding to the component, the documentation window is NOT updated.

**Comment by ratiud** [comment]
I think that the problem is that when an entity has documentation (attribute) then clicking on its corresponding diagram box selects the documentation (attribute) and NOT the entity itself (picture below)

![image](https://user-images.githubusercontent.com/74968924/126112802-0db05d38-0c78-4b23-be00-0ad79ee5b7ca.png)

**Comment by ratiud** [comment]
further investigation shows that the above situation is another bug ... actually when I have a reference to a component with attached documentation, the docu is not shown 

![image](https://user-images.githubusercontent.com/74968924/126114184-43b93353-b378-4e7d-928c-eda9b1fd4fc4.png)


if I change to textual notation, the selected node is Assembly

![image](https://user-images.githubusercontent.com/74968924/126114046-353b72a3-650a-457b-9105-9331f20d3109.png)

**Comment by slisson** [comment]
The attributed node is now shown in the inspector instead of the NodeAttribute.

**Comment by ratiud** [comment]
Thank you for this - selection of node (instead of the attribute works). But, if I attached a documentation to a *Port* then the documentation attached to the port is NOT updated. If I click on the port, in inspector is displayed correctly that a port is selected, however, the documentation window does NOT see that I selected a port (page below).

![image](https://user-images.githubusercontent.com/74968924/126157127-ccee4d2b-96da-48ae-baef-dfadb706f4de.png)

**Comment by slisson** [comment]
I think I fixed it. Please check again.

**Comment by ratiud** [comment]
now the documentation of ports is shown, but NOT the documentation of boxes (instance of some components)
![image](https://user-images.githubusercontent.com/74968924/126348924-f6eed80b-e5ca-40f5-956f-e09a491fbe80.png)

**Comment by slisson** [comment]
Your component instance has to implement IDocumentable and return the documentation of the component declaration. Here is an example:
<img width="749" alt="Screenshot 2021-07-22 at 09 22 43" src="https://user-images.githubusercontent.com/1543361/126602974-0c55fa8f-5cd9-4817-b85f-4d1a9dd4559b.png">

**Comment by ratiud** [comment]
This works, thank you Sascha!
