### ISSUE TITLE
Shadowmodels plugin in Modelix branch has not changed plugin version

### ISSUE THREAD

**Issue by ftomassetti** [JetBrains/MPS-extensions#445]
In the Modelix branch I think the Shadowmodels plugin has been slightly changed but the version number has remained the same. This means that the standard Shadowmodels plugin and the one in the Modelix branch cannot be easily distinguished

**Comment by cmoine** [comment]
Incriminated change is the following:
![image](https://user-images.githubusercontent.com/3293928/132645379-e84a9046-5804-4e86-a25b-d47c892632c1.png)

361a106c3781d57888042cc8be56a16ea468efc8

This change would require a version change number in the plugin. btw the version is still 2018.1. I think this should definitely be incremented to 2020.

**Comment by cmoine** [comment]
Shouldn't we use ${versionNumber} here?
![image](https://user-images.githubusercontent.com/3293928/132646342-0fe274c4-735e-40a1-a774-e18520be1ec2.png)
