### ISSUE TITLE
Make Parser.DEFAULT_TIMEOUT configurable

### ISSUE THREAD

**Issue by szabta89** [JetBrains/MPS-extensions#450]
Currently, there is no way to set a custom timeout value for the grammar cells `Parser`, as the field is `private static final`. Would it be okay to change this field to `public static`? The only other option would be to use very hacky reflection to change the value, but I would rather not do that.

**Comment by szabta89** [comment]
What do you think @slisson ?

**Comment by wsafonov** [comment]
How about making internal configurable values available through the IntelliJ registry?

**Comment by slisson** [comment]
You can do that, but I doubt it solves your problem (or creates a new one). The value is already very high. An exception because of a timeout usually requires a change of the parsing algorithm.

**Comment by szabta89** [comment]
@slisson  I dont know how this value actually translates to time duration, as the handling of the timeout via `countDown` seems more like using up an allocated number of "fuel" throughout the computation. In my use case, the default "timeout" is used up in 300 ms. The current approach is not ideal: an exception is thrown which does not make it to MPS, as it only shows up in the logs, and the user is not notified in any way about the failure to find a new parse tree. Instead, the original subtree is left intact and the new complete tree may not even obey precedence/associativity.

**Comment by szabta89** [comment]
Setting the timeout to a high value may actually freeze the UI, but it at least ensures correctness. Changing the parser algorithm seems like a fundamental refactoring.

**Comment by alexanderpann** [comment]
I am closing this issue because your commit is included in the repo. Let's reopen if there are still issues or better solutions.
