### ISSUE TITLE
EdgeRelayoutAfterMove editor test in test.de.itemis.editor.diagram.solution fails

### ISSUE THREAD

**Issue by brucetrask2** [JetBrains/MPS-extensions#468]
Not sure if it should fail or not but just wondering. It seems to be failing when I think it should pass. I am runing 2021.1 and the mps extensions from the head. If I change it to asser true it passes but that seems to be what the result is defaulted to in the code. 
<img width="1726" alt="Screen Shot 2021-11-18 at 8 33 45 PM" src="https://user-images.githubusercontent.com/83460213/142542527-b1d1dfd4-7b1f-46ee-a415-1f7138e15f84.png">

**Comment by alexanderpann** [comment]
This test was not needed anymore and was removed.
