### ISSUE TITLE
Shadow Models memory usage warning (when not enabled)

### ISSUE THREAD

**Issue by tomb50** [JetBrains/MPS-extensions#469]
Shadow models RepositoryMirror using memory despite Shadows Model not being enabled.

Ran into a memory usage warning whilst using MPS (with MPS extensions installed as a project library). The high usage looks to be referencing the shadow models repository

![image](https://user-images.githubusercontent.com/2701339/142878575-0debc63d-882b-4a92-9bd9-b133288a2d65.png)

Shadow Repository is not enabled through the IDE Tools -> Shadows Models menu

**Comment by alexanderpann** [comment]
@tomb50 do you still run into the issue? Most of the shadow model memory leaks should be fixed in the meantime.

**Comment by tomb50** [comment]
Hi @alexanderpann 

No we haven't seen this issue for a while, we bumped MPS versions and also swapped from MPS Extensions to using Mbeddr Platform + IETS3 - so I don't think this is a valid issue anymore, it must have been fixed along the way :-D

Thanks!
Tom
