### ISSUE TITLE
Collapsible editors are extremely slow when they are imbricated at multiple levels

### ISSUE THREAD

**Issue by danielratiu** [JetBrains/MPS-extensions#570]
I am representing a hierarchical structure via Collapsible editors in order to allow users to incrementally navigate.
The editors get very slow once I expand more than 3 times - refreshing takes 10+ seconds on a very performant machine.

![image](https://user-images.githubusercontent.com/1437141/212469781-c717f331-a6d6-4fde-9d5c-1021e458c64b.png)

**Comment by alexanderpann** [comment]
I am closing because the PR was merged.
