### ISSUE TITLE
Find (CMD+F) loses focus when diagram was active

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#59]
From mbeddr.core created by [slisson](https://github.com/slisson) : mbeddr/mbeddr.core#1735  

After typing the first character in the find textbox it loses the focus.

**Comment by alexanderpann** [comment]
Closing because the issue was probably fixed in one of the following focus related commits:
7ad274d5633b2ae93506200aad3485583152cca6, d231518b75cbfd1a7b40312b83219d3a81a3d2df, 91addab950ce7f30956322c2aa3d9f15a3ff93df, c56b6541c750cd9fddb587e6505b5bfab4c3b984
