### ISSUE TITLE
MPS-Extensions plugins not available in marketplace anymore

### ISSUE THREAD

**Issue by eugenschindler** [JetBrains/MPS-extensions#596]
Trying to install one of the plugins from MPS-Extensions (and actually tried several), but they are not available in marketplace (anymore?). Using MPS 2021.3.

**Comment by alexanderpann** [comment]
@mvlassiev did not trigger the upload script for 2021.3.2 and 2022.2, you have to ask him about this.

**Comment by alexanderpann** [comment]
Should be fixed now.
