### ISSUE TITLE
diagram language does not reexport diagram.runtime solution

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#60]
From mbeddr.core created by [DomenikP](https://github.com/DomenikP) : mbeddr/mbeddr.core#1743  

The de.itemis.mps.editor.diagram language does not reexport its runtime solution (de.itemis.mps.editor.diagram.runtime). Other MPS projects using the diagram language will face compilation problems in the command-line build, since the Java classes from the diagram.runtime solution are not added to the classpath.

**Comment by alexanderpann** [comment]
Closing because this was fixed years ago.
