### ISSUE TITLE
GrammarCells: flag cells should be automatically undoable via code completion menu

### ISSUE THREAD

**Issue by alexanderpann** [JetBrains/MPS-extensions#621]
Normally, you enter some specific text and the flag is set to true. When you delete the displayed text, the flag is set to false (= removed). This works well when the flag is used like the public modifier in baselanguage. For example:
`boolean a = true` -> enter "public" -> `public boolean a = true`
When the editor changes heavily when the flag is set, the flag doesn't feel like a flag anymore and as a user I would try to undo it using the code completion menu, the same way I have added it. The user would have to delete the flag of course.
Example:  `default component A` -> enter "composition". -> `component composition A`.
I think there should be a automatically created code completion menu entry with a customizable description (e.g., remove composition) that lets you set the flag to false in addition to the normal way of deleting the flag.

**Comment by slisson** [comment]
There are users that expect things to be removed when they type something? That doesn't sound intuitive. Does the example describe the actual use case or is this too simplified to understand why this is necessary? I would like to see the actual use case.

**Comment by alexanderpann** [comment]
I've changed the wording a bit, but yes, this is the actual use case. I am not sure if my proposed change is really a good idea, and I also don't find the use case very intuitive. Normally, I would also expect the flag to not change the text, but there might be cases where the new wording comes from a specific domain. Then you can't use flags like modifiers the way we are used to it.

**Comment by alexanderpann** [comment]
I'll close the ticket myself. If there is a need for this use case, it can be implemented as an intention in the project that needs this.
