### ISSUE TITLE
Allow to specify read-only in nodesQeury

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#65]
From mbeddr.core created by [joswarmer](https://github.com/joswarmer) : mbeddr/mbeddr.core#1472  

When a nodesQuery returns nodes coming from elsewhere in the AST is is useful to be able to define that the node (its shape and contents) is read-only in this editor.
This helps to manage diagram editors where nodes are visible in more than one edtor.

**Comment by alexanderpann** [comment]
I guess this is obsolete because by default the `read-only` property is set to true for the cell.
