### ISSUE TITLE
Copy reference to EditorCell when copying from Cell Explorer

### ISSUE THREAD

**Issue by alamqadem** [JetBrains/MPS-extensions#658]
As part of a pagination extension that I'm working on, the following feature would be useful.
For the structure, we can inspect in the Logical View and by copying on a node, a reference to that node is copied and this can be used programmatically in the Console.

<img src="https://github.com/JetBrains/MPS-extensions/assets/10254994/5ddaf288-1db5-4fb3-a328-50a7a6072e85" width=75% height=75%>

<img src="https://github.com/JetBrains/MPS-extensions/assets/10254994/1865af28-8cc4-459a-9857-e201fb17e663" width=75% height=75%>

Similarly we can inspect the editor cells with `Language Debug/Show Cell in Explorer`.

<img src="https://github.com/JetBrains/MPS-extensions/assets/10254994/c4355e80-125c-4678-a461-5bdfd387c118" width=50% height=50%>

At the moment copying on a node in the cell explorer doesn't copy a reference to the corresponding `EditorCell_x` class.
We would like to be able to get a reference to an editor cell from the Cell explorer and then be able to use it programmatically in the Console.

<img src="https://github.com/JetBrains/MPS-extensions/assets/10254994/a5bf62d0-0117-445d-801e-2c3c7ce1a80c" width=75% height=75%>

**Comment by alexanderpann** [comment]
Implemented in #728
