### ISSUE TITLE
Compilation error in port definition

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#68]
From mbeddr.core created by [joswarmer](https://github.com/joswarmer) : mbeddr/mbeddr.core#1478  

In the diagram editor specification you van specify the `label` of a `port`. If the expression entered is not of type `string` the langauge built will give a compilation error:

```
The constructor Port(<<expression type>>) is undefined,
```

There shoukld be a check on the type of the `label` expression to ensure it always conforms to string.

**Comment by alexanderpann** [comment]
Fixed in [ab8be85](https://github.com/JetBrains/MPS-extensions/commit/ab8be85f1c49b6b391b4e1124d026952a5b66eff).
