### ISSUE TITLE
celllayout: editor doesn't show the full node vertically

### ISSUE THREAD

**Issue by alamqadem** [JetBrains/MPS-extensions#681]
## Description

Given an indent collection containing an horizontal collection, if the internal collection is large enought this is reported on a new line.

<img width="500" alt="image" src="https://github.com/JetBrains/MPS-extensions/assets/10254994/afe4ad18-feff-466e-8fd6-8d0d77c97c04">

Now after a certain size the editor doesn't display the full node, in fact the scroll-bar doesn't allow to scroll down to see the last part of the node.
I suspect that the height of the resulting node it's not calculated correctly ([RootConcept](http://127.0.0.1:63320/node?ref=r%3A6d99c7cf-6f56-4303-a16b-bda0ab8fbe78%28de.itemis.mps.editor.celllayout.sandbox%29%2F4615632674300010191)).

<img width="500" alt="image" src="https://github.com/JetBrains/MPS-extensions/assets/10254994/8bb2653e-3e78-4b94-80de-5ad42c191383">

Disabling the `LayoutInterceptor` the node is shown correctly.

<img width="500" alt="image" src="https://github.com/JetBrains/MPS-extensions/assets/10254994/4528ce2b-c026-4030-bea5-b97c5e6581e6">

## Reproducer

I've attached a reproducer in the following branch `bug/celllayout-cell-height-not-correct` based on `maintenance/mps20213`.

**Comment by alamqadem** [comment]
Using the `Editor Cell Explorer` I can check the height calculated for the cell with the `LayoutInterceptor` on, which is 84.

<img width="500" src="https://github.com/JetBrains/MPS-extensions/assets/10254994/2874c5b8-f134-4fe9-afc0-0d1cbf5dc3de">

And without the interceptor active I get 105.

<img width="500" src="https://github.com/JetBrains/MPS-extensions/assets/10254994/8b14b484-fc36-48d9-9ad8-5e1a6c5a0257">

**Comment by alexanderpann** [comment]
Not reproducible anymore. This issue was fixed a while ago.
