### ISSUE TITLE
Diagram: Loop edges cannot be layouted

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#73]
From mbeddr.core created by [slisson](https://github.com/slisson) : mbeddr/mbeddr.core#1424  

Edges with the same source and target are not layouted by the libavoid layouter. Also it is not possible to manually layout these edges, when they have no bend points, because their size is then 0.

**Comment by alexanderpann** [comment]
This issue is outdated since this layouter is not used anymore and the issue was probably fixed in #52.
