### ISSUE TITLE
GrammarCells: broken reference 'conceptDeclaration' in [actualArgument] ConceptIdRefExpression

### ISSUE THREAD

**Issue by mutex1980** [JetBrains/MPS-extensions#737]
In a vanilla build (with build language`ant generate`) following exactly the reference structure for binary expression (left out the substitute cell for minimality):

![image](https://github.com/JetBrains/MPS-extensions/assets/21034522/ab3c2378-2cb8-460b-acde-b517feeac8b9)

leads to error:

```
mps  |  [mps.make] broken reference 'conceptDeclaration' in [actualArgument] ConceptIdRefExpression null[1787432944212145825] in math.editor@4_3 (target model is null)

mps  |  [mps.make] -- -- was input node: [actualArgument] ConceptIdRefExpression null[1787432944212145825] in math.editor@4_3

mps  |  [mps.make] broken reference 'conceptDeclaration' in [actualArgument] ConceptIdRefExpression null[1787432944212146872] in math.editor@4_3 (target model is null)

mps  |  [mps.make] -- -- was input node: [actualArgument] ConceptIdRefExpression null[1787432944212146872] in math.editor@4_3

mps  |  [mps.make] model 'math.editor@3_1' has been generated with errors
```

Within MPS I can randomly successfully rebuild the whole project (especially if I rebuild the BinaryExpression editor component step-by-step in the UI from scratch and perform rebuilds after each step), but if I restart MPS then with cleaned caches and delete all source_gen, classes_gen and source_gen.caches project wide, I can reproduce the vanilla ant build problem also within the IDE:

![image](https://github.com/JetBrains/MPS-extensions/assets/21034522/47d09c94-7d11-4b2f-acb2-079226d6beab)

The complaining transformation step seems to have problems with the wrap cells in a transient model:

![image](https://github.com/JetBrains/MPS-extensions/assets/21034522/cc1b0414-84cb-4516-9df8-520fd91bf424)

And the IDE error message log double clicked points to this location in the generated SideTransformation Menu (see cursor position):

![image](https://github.com/JetBrains/MPS-extensions/assets/21034522/060a1543-f20c-4862-aa9a-6c6ceae85bde)

Hovering this position says:

`
Unresolved reference: BaseConcept
`

Any attempts to include mps.lang.core (where BaseConcept is defined) to any language dependencies didn't help. Is this a bug or did I do something wrong?

MPS: 2023.2, Build #MPS-232.10072.781
MPS-Extensions: 2023.2.2697.35c375c 

Workaround:

- remove the gramarcells completly from binary expression editor
- define right side transforms for operators individually
- vanilla build works as expected again -> CI is possible

**Comment by alexanderpann** [comment]
I can have a look at it if you have a sample project but at the time you created the ticket the version for 2023.2 was not even released so you might have mixed MPS versions by accident.

**Comment by blue995** [comment]
I'm facing the same problem since 2022.2

**Comment by alexanderpann** [comment]
Regarding the version that you are using: It seems like we published some pre-releases by accident. The newest official release is 2023.2.2728.44d39ee.
I have not seen any similar issues while migrating our other MPS platforms, that's why I suspect there is something wrong with your setup. If you have a sample project, I could test it but the Grammar Cells sandbox also works in this repository.

**Comment by alexanderpann** [comment]
I'll close this ticket as no further information was provided and it looks like a mix-up of MPS versions to me. Please reopen if it is still an issue.
