### ISSUE TITLE
Colors in diagram editor definition not legible

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#74]
From mbeddr.core created by [joswarmer](https://github.com/joswarmer) : mbeddr/mbeddr.core#1428  

In the diagram definition the background color of "diagram" and "diagram box" etc .  is dark grey,  and the foreground color is purple. I cannot read this as the contrast between the colors is not high enough.
Solution: change background color to e.g. white.

**Comment by alexanderpann** [comment]
Fixed in 7a46f777e5efd3b6bc08258139abde66fd42ca53.
I don't understand the comment. It looks unrelated to the original issue.
