### ISSUE TITLE
de.itemis.mps.editor.diagram.runtime depends on both IDEA guava and q60 guava

### ISSUE THREAD

**Issue by enikao** [JetBrains/MPS-extensions#858]
We're using `com.mbeddr.platform` version `2022.3-2022.3.24305.b0eebaa`.

`de.itemis.mps.editor.diagram.runtime.jgraph` uses `Multimap` from `de.q60.mps.collections.libs/com.google.common.collect`.

`de.itemis.mps.editor.diagram.runtime/org.eclipse.elk.*` uses `Multimap` from `MPS.IDEA/com.google.common.collect`.

Classloaders can get very confused by this.

**Comment by alexanderpann** [comment]
The issue is fixed in #850. Let me know if there are still similar issues.

**Comment by enikao** [comment]
Thanks @alexanderpann for the swift fix.
