### ISSUE TITLE
When cloning a model with a graphical editor, layout is not preserved

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#86]
From mbeddr.core created by [eugenschindler](https://github.com/eugenschindler) : mbeddr/mbeddr.core#1421  

Steps to reproduce:
-Make a model with a graphical editor in it
-Layout the model manually
-Clone the model

Result: the layout in the cloned model is completely lost with respect to the original model

Some ideas:
-why is the layout not part of the model contents? is that a conscious choice?
-in how far can layout be seen as something with meaning?
-is it necessary to force the user to auto-layout or is the layout also seen as something that adds hints to understand the model?

**Comment by alexanderpann** [comment]
Workaround with MPS 2022.3 and 2023.2.2 based on experimental UUIDS assuming we have a diagram _`BaseDiagram`_ with boxes `Box` and edges _`Edge`._ Node identity support must be enabled in mps.vmoptions: `-Dmps.nodeuid=true`

Set the ID of the diagram, box, and edge cell to _`thisNode.get uuid` in_ the inspector of the corresponding diagram cell (you have to import _`jetbrains.mps.lang.smodel)`._ Create a new plugin solution with the following content:

![](https://github.com/user-attachments/assets/5108f688-0602-4d81-a85d-68f2caf4bfcb)

![](https://github.com/user-attachments/assets/568dd287-a8d9-4805-8a04-afa4d3e2f3c1)

When cutting and pasting the diagram node, using the action _Clone Root,_ or cloning the model, the layout data will be preserved.

When copying and pasting a new ID will be issued and the layout data won't be preserved.
