### ISSUE TITLE
Layout of red buttons wrong in treenotation editors with MPS2023.2 

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#894]
The treenotation editor shows red buttons allowing the user to delete tree nodes. Example from IETS3.core (on `maintenance/mps20223`):

![image](https://github.com/user-attachments/assets/c4407bef-69ee-48ed-92db-ca65e1011890)

On `maintenance/mps20232`, this looks differently (using MPS 2023.2.1 and latest IETS3.Core):

![image](https://github.com/user-attachments/assets/adb55c5b-9d09-45f8-99b4-a92520df09e6)

The red buttons' position is layouted wrong. Expected: Layout as in the first screenshot.

Remark:  This is not a IETS3-Variability specific problem, as the problem is shown also in different DSLs using the treenotation. Example:

![image](https://github.com/user-attachments/assets/165f9960-6b8f-4c92-be17-fe61816d0819)

**Comment by alexanderpann** [comment]
It looks like 4b3e10a fixed one layouting issue but caused a new issue where the delete buttons are not correctly layouted.
