### ISSUE TITLE
Subdiagrams are outside their box after autolayout and zoom

### ISSUE THREAD

**Issue by kbirken** [JetBrains/MPS-extensions#90]
From mbeddr.core created by [slisson](https://github.com/slisson) : mbeddr/mbeddr.core#1411  

![pasted image at 2016_06_29 04_40 pm](https://cloud.githubusercontent.com/assets/1543361/16457004/4d2e9aea-3e1a-11e6-8c26-6d73f65f7c77.png)

"This happed after I pressed the +, - and auti-layout buttons a few times.
When I click on the empty grey box,  the contents suddenly jumps into it again"

**Comment by alexanderpann** [comment]
We need to check if #554 already fixes this issue.

**Comment by alexanderpann** [comment]
It is not reproducible for me with the [Nested Diagram example](http://127.0.0.1:63320/node?ref=r%3Aeef2ce22-1d12-4507-9261-7f835a81e787%28de.itemis.mps.editor.diagram.demo.elk.sandbox%29%2F5731047739261699664&project=mps-extensions). Seems to be fixed.
